### Q1. Write a Python Program to Add Two Matrices?

In [1]:
#solution 1
mat1 = [[1,6,4],
        [4,5,6],
        [7,6,9]]

mat2 = [[2,5,4],
        [5,8,7],
        [8,3,1]]

sumMat = [[0,0,0],
          [0,0,0],
          [0,0,0]]

sumMat = [[mat1[i][j] + mat2[i][j] for j in range(len(mat1[0]))] for i in range(len(mat1))]
print("The Sum of two matrix {}  and {}  is \n{} ".format(mat1,mat2,sumMat))

The Sum of two matrix [[1, 6, 4], [4, 5, 6], [7, 6, 9]]  and [[2, 5, 4], [5, 8, 7], [8, 3, 1]]  is 
[[3, 11, 8], [9, 13, 13], [15, 9, 10]] 


In [2]:
#solution 2
import numpy as np

mat1 = np.array([[1,6,4],
        [4,5,6],
        [7,6,9]])
mat2 = np.array([[2,5,4],
        [5,8,7],
        [8,3,1]])

sumMat = np.add(mat1,mat2)
print("The Sum of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,sumMat))

The Sum of two matrix 

[[1 6 4]
 [4 5 6]
 [7 6 9]]  and 

[[2 5 4]
 [5 8 7]
 [8 3 1]]  is 

[[ 3 11  8]
 [ 9 13 13]
 [15  9 10]] 


### Q2. Write a Python Program to Multiply Two Matrices?

In [3]:
import numpy as np

mat1 = np.array([[1,2,4],
        [4,5,6],
        [7,8,9]])
mat2 = np.array([[2,3,4],
        [5,6,7],
        [8,9,1]])

sumMat = np.dot(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,sumMat))

The product of two matrix 

[[1 2 4]
 [4 5 6]
 [7 8 9]]  and 

[[2 3 4]
 [5 6 7]
 [8 9 1]]  is 

[[ 44  51  22]
 [ 81  96  57]
 [126 150  93]] 


### Q3. Write a Python Program to Transpose a Matrix?

In [6]:
import numpy as np


mat = np.array([[2,3,4],
        [5,6,7],
        [8,9,1]])
Trans= np.transpose(mat)

In [7]:
Trans

array([[2, 5, 8],
       [3, 6, 9],
       [4, 7, 1]])

### Q4. Write a Python Program to Sort Words in Alphabetic Order?

In [9]:
str = input("Enter some string: ")

words = str.split()
words.sort()
for word in words:
    print(word)

Enter some string: live like Lion
Lion
like
live


### Q5. Write a Python Program to Remove Punctuation From a String?

In [10]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

str = input("Enter some string with panctuations")

# remove punctuation from the string
no_punct = ""
for char in str:
    if char not in punctuations:
        no_punct = no_punct + char

# display the unpunctuated string
print(no_punct)

Enter some string with panctuations(Name i{s} B{o}n[D)
Name is BonD
